name: vockify
description: A simple Quiz frontend/mobile application for learning languages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^5.0.0
  redux_epics: ^0.15.1
  flutter_redux: ^0.10.0
  built_value: ^8.6.2
  built_collection: ^5.1.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  oauth2: ^2.0.2
  flutter_web_auth: ^0.5.0
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.0
  path_to_regexp: ^0.4.0
  quiver: ^3.2.1
  # receive_sharing_intent: ^1.4.5
  carousel_slider: ^4.2.1
  reselect: ^0.5.0
  easy_debounce: ^2.0.3
  amplitude_flutter: ^3.16.0
  # assets_audio_player:
  #   git:
  #     url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
  #     ref: b49a4360f6a7f182d4a6e23ebcdbf43ad570913b
  sentry_flutter: ^7.9.0

dev_dependencies:
  build_runner: ^2.4.6
  built_value_generator: ^8.6.2
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/btn_google_signin_dark_normal_web@2x.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
