name: vockify
description: A simple Quiz frontend/mobile application for learning languages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1
  oauth2: ^2.0.2
  flutter_web_auth: ^0.5.0
  shared_preferences: ^2.2.1
  font_awesome_flutter: '>= 4.7.0'
  carousel_slider: ^4.2.1
  easy_debounce: ^2.0.3
  amplitude_flutter: ^3.16.0
  sentry_flutter: ^7.9.0
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  provider: ^6.1.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.7
  built_value_generator: ^8.6.2
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  drift_dev: ^2.11.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/btn_google_signin_dark_normal_web@2x.png
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Italic.ttf
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
